image: python:3.10-alpine

pages:
  stage: deploy
  script:
    - pip install toml xlsxwriter
    - python TOML-JSON.py
    - python TOML-excel.py
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
