[topics."Input Devices"]
comment = "########################################################"

[topics."Input Devices".sources.Digi-Key]
comment = "========================================================"
URL = "https://www.digikey.com"
currency = "USD"

[[topics."Input Devices".sources.Digi-Key.categories.potentiometer]]
comment = "--------------------------------------------------------"
description = "TRIMMER 10K OHM 0.25W GW TOP ADJ"
item = "ST4ETB103CT-ND"
URL = "https://www.digikey.com/en/products/detail/nidec-copal-electronics/ST4ETB103/738213"
price = 0.95
quantity = 25

[[topics."Input Devices".sources.Digi-Key.categories.color]]
comment = "--------------------------------------------------------"
description = "RGBW COLOR SENSOR I2C INTERFACE"
item = "VEML6040A3OGCT-ND"
URL = "https://www.digikey.com/en/products/detail/vishay-semiconductor-opto-division/VEML6040A3OG/5168308"
price = 1.80
quantity = 25

[[topics."Input Devices".sources.Digi-Key.categories.distance]]
comment = "--------------------------------------------------------"
description = "VL53L1X TOF DISTANCE SNSR W/VREG"
item = "2183-3415-ND"
URL = "https://www.digikey.com/en/products/detail/pololu-corporation/3415/10451121"
price = 11.95
quantity = 10

[[topics."Input Devices".sources.Digi-Key.categories."magnetic field"]]
comment = "--------------------------------------------------------"
description = "Hall Effect Sensor X, Y, Z Axis PG-TSOP6-6-8"
item = "TLE493DA2B6HTSA1CT-ND"
URL = "https://www.digikey.com/en/products/detail/infineon-technologies/TLE493DA2B6HTSA1/9808570"
price = 1.99
quantity = 25

[[topics."Input Devices".sources.Digi-Key.categories.magnets]]
comment = "--------------------------------------------------------"
description = 'MAGNET 0.5"DIA X 0.125"H CYL'
item = "8022"
URL = "https://www.digikey.com/en/products/detail/radial-magnets-inc/8022/555326"
price = 0.72760
quantity = 50

[[topics."Input Devices".sources.Digi-Key.categories.magnets]]
description = 'MAGNET 0.25"DIA X 0.125"H CYL'
item = "8193"
URL = "https://www.digikey.com/en/products/detail/radial-magnets-inc/8193/555328"
price = 0.23400
quantity = 100

[[topics."Input Devices".sources.Digi-Key.categories.IMU]]
comment = "--------------------------------------------------------"
description = "MINIMU-9 V5 GYRO ACCEL & COMPASS"
item = "2183-2738-ND"
URL = "https://www.digikey.com/en/products/detail/pololu-corporation/2738/10451104"
price = 26.61
quantity = 10

[topics."Output Devices"]
comment = "########################################################"

[topics."Output Devices".sources.Digi-Key]
comment = "========================================================"
URL = "https://www.digikey.com"
currency = "USD"

[[topics."Output Devices".sources.Digi-Key.categories."motor drivers"]]
comment = "--------------------------------------------------------"
description = "IC MOTOR DRIVER 8V-40V 8SOIC"
item = "A4950ELJTR-T"
URL = "https://www.digikey.com/product-detail/en/allegro-microsystems-llc/A4950ELJTR-T/620-1400-1-ND"
price = 2.552
quantity = 25

[[topics."Output Devices".sources.Digi-Key.categories."motor drivers"]]
attribute = "alternate"
description = "50V/3A BRUSHED MOTOR DRIVER"
item = "TB67H451FNG,EL"
URL = "https://www.digikey.com/en/products/detail/TB67H451FNG%2cEL/264-TB67H451FNGELCT-ND/11568783"
price = 1.0971
quantity = 25

[[topics."Output Devices".sources.Digi-Key.categories."motor drivers"]]
description = "35V, 1A BIPOLAR STEPPER MOTOR DR"
item = "DRV8428PWPR"
URL = "https://www.digikey.com/en/products/detail/texas-instruments/DRV8428PWPR/13563046"
price = 2.676
quantity = 25

[[topics."Output Devices".sources.Digi-Key.categories."motor drivers"]]
description = "2A DUAL H-BRIDGE MOTOR DRIVER"
item = "DRV8847PWPR"
URL = "https://www.digikey.com/en/products/detail/texas-instruments/DRV8847PWPR/9954204"
price = 1.8948
quantity = 25

[[topics."Output Devices".sources.Digi-Key.categories."motor drivers"]]
description = "IC MOTOR DRIVER 5V-16V 16HTSSOP"
item = "DRV11873PWPR"
URL = "https://www.digikey.com/en/products/detail/texas-instruments/DRV11873PWPR/3903327"
price = 1.8392
quantity = 25

[topics."Output Devices".sources.Amazon]
comment = "========================================================"
URL = "https://www.amazon.com"
currency = "USD"

[[topics."Output Devices".sources.Amazon.categories.displays]]
comment = "--------------------------------------------------------"
description = "20X4 LCD Display LCD Screen Serial with I2C Adapter"
item = "HiLetGo"
URL = "https://www.amazon.com/HiLetgo-Backlight-Display-Arduino-MEGA2560/dp/B01DKETWO2"
price = 8.59
quantity = 10

[[topics."Output Devices".sources.Amazon.categories.displays]]
description = "5PCS OLED Display Module, 0.96 Inch I2C Serial 128 x 64 with SSD1306"
item = "PEMENOL"
URL = "https://www.amazon.com/PEMENOL-Display-0-96inch-Raspberry-Microcontroller/dp/B07F3KY8NF"
price = 22.50
quantity = 5

[[topics."Output Devices".sources.Amazon.categories.displays]]
description = "TFT LCD Screen Display 1.3inch 240x240 IPS 65K Full Color 3.3V with SPI Interface ST7789 IC Driver"
item = "MakerFocus"
URL = "https://www.amazon.com/MakerFocus-Display-1-3inch-Interface-Routines/dp/B07P9X3L7M"
price = 11.99
quantity = 10
