# FOOD
[[items]]
purpose = [ "Food",]
source = [ "Hackaday",]
category = [ "Food Processing",]
description = [ "Open Source Fermenter",]
item = [ "Open Source Fermenter",]
URL = [ "https://hackaday.io/project/186650-an-open-source-fermenter",]
manufacturer = []
price = [ 0 ]
quantity = [ 0,]
[items.attributes]
"tariff code" = ""
"country of origin" = ""
"license" = "CC BY-NC-SA 4.0"

[[items]]
purpose = [ "Food",]
source = [ "Hackaday",]
category = [ "Decentralised Farming",]
description = [ "Dibbling Plate, Put those holes in the soil quick",]
item = [ "Dibbling Plate",]
URL = [ "https://hackaday.io/project/167679-dibbling-plate-put-those-holes-in-the-soil-quick",]
manufacturer = []
price = [ 0 ]
quantity = [ 0,]
[items.attributes]
"tariff code" = ""
"country of origin" = ""
"license" = "CC BY-NC-SA 4.0"

[[items]]
purpose = [ "Food",]
source = [ "Hackaday",]
category = [ "Decentralised Farming",]
description = [ "Drop Seeder, Put those seeds in the soil quick",]
item = [ "Drop Seeder",]
URL = [ "https://hackaday.io/project/168051-drop-seeder-put-those-seeds-in-the-soil-quick",]
manufacturer = []
price = [ 0 ]
quantity = [ 0,]
[items.attributes]
"tariff code" = ""
"country of origin" = ""
"license" = "CC BY-NC-SA 4.0"

[[items]]
purpose = [ "Food",]
source = [ "Misc",]
category = [ "Decentralised Farming",]
description = [ "Precision agriculture CNC",]
item = [ "Farmbot genesis",]
URL = [ "https://farm.bot/",]
manufacturer = []
price = [ 0 ]
quantity = [ 0,]
[items.attributes]
"tariff code" = ""
"country of origin" = ""
"license" = "CC BY-NC-SA 4.0"


# HOUSING
[[items]]
purpose = [ "Housing",]
source = [ "Hackaday",]
category = [ "Clothing",]
description = [ "Braiding machine",]
item = [ "3D printed braiding machine",]
URL = [ "https://hackaday.io/project/191583-3d-printed-braiding-machine",]
manufacturer = []
price = [ 0 ]
quantity = [ 0,]
[items.attributes]
"tariff code" = ""
"country of origin" = ""
"license" = "Commercial"

[[items]]
purpose = [ "Housing",]
source = [ "Misc",]
category = [ "Building",]
description = [ "Multipurpose machine",]
item = [ "The multimachine",]
URL = [ "https://opensourcemachine.org/",]
manufacturer = []
price = [ 0 ]
quantity = [ 0,]
[items.attributes]
"tariff code" = ""
"country of origin" = ""
"license" = ""

# MEDICAL
[[items]]
purpose = [ "Medical",]
source = [ "Misc",]
category = [ "Protective Gear",]
description = [ "Protective mask",]
item = [ "3DMASK",]
URL = [ "https://ohwr.org/project/3dmask/-/wikis/home",]
manufacturer = []
price = [ 0 ]
quantity = [ 0,]
[items.attributes]
"tariff code" = ""
"country of origin" = ""
"license" = ""

[[items]]
purpose = [ "Medical",]
source = [ "Appropedia",]
category = [ "Protective Gear",]
description = [ "Conversion of Self-Contained Breathing Apparatus Mask to Open Source Powered Air-Purifying Particulate Respirator for Fire Fighter COVID-19 Response",]
item = [ "Self-contained breathing apparatus",]
URL = [ "https://www.appropedia.org/Conversion_of_Self-Contained_Breathing_Apparatus_Mask_to_Open_Source_Powered_Air-Purifying_Particulate_Respirator_for_Fire_Fighter_COVID-19_Response",]
manufacturer = []
price = [ 0 ]
quantity = [ 0,]
[items.attributes]
"tariff code" = ""
"country of origin" = ""
"license" = ""

[[items]]
purpose = [ "Medical",]
source = [ "Appropedia",]
category = [ "Imaging",]
description = [ "Free and open-source automated 3-D microscope",]
item = [ "Automated 3D microscope",]
URL = [ "https://www.appropedia.org/Conversion_of_Self-Contained_Breathing_Apparatus_Mask_to_Open_Source_Powered_Air-Purifying_Particulate_Respirator_for_Fire_Fighter_COVID-19_Response",]
manufacturer = []
price = [ 0 ]
quantity = [ 0,]
[items.attributes]
"tariff code" = ""
"country of origin" = ""
"license" = ""

[[items]]
purpose = [ "Medical",]
source = [ "Appropedia",]
category = [ "Imaging",]
description = [ "Free and open-source automated 3-D microscope",]
item = [ "Automated 3D microscope",]
URL = [ "https://www.appropedia.org/Conversion_of_Self-Contained_Breathing_Apparatus_Mask_to_Open_Source_Powered_Air-Purifying_Particulate_Respirator_for_Fire_Fighter_COVID-19_Response",]
manufacturer = []
price = [ 0 ]
quantity = [ 0,]
[items.attributes]
"tariff code" = ""
"country of origin" = ""
"license" = ""

# purposes
[purposes."Food"]
program = [ "",]
URL = [ "",]

[purposes."Housing"]
program = [ "",]
URL = [ "",]

[purposes."Medical"]
program = [ "",]
URL = [ "",]

# sources
[sources."Hackaday"]
URL = [ "https://www.prusa3d.com",]
currency = [ "USD",]
currency_symbol = [ "$",]

[sources."Appropedia"]
URL = [ "https://www.appropedia.org/",]
currency = [ "USD",]
currency_symbol = [ "$",]

[sources."Misc"]
URL = [ "https://farm.bot",]
currency = [ "USD",]
currency_symbol = [ "$",]
